name: retail_data_platform
version: "1.0.0"
config-version: 2

profile: retail_data_platform

require-dbt-version:
  - ">=1.12.0"
  - "<1.13.0"

model-paths:
  - models

test-paths:
  - tests

macro-paths:
  - macros

target-path: target

clean-targets:
  - target
  - dbt_packages
  - logs

models:
  retail_data_platform:
    staging:
      +materialized: view

    silver:
      +materialized: table

    gold:
      +materialized: table