CREATE TEMPORARY TABLE bq_customers_cdc (
    `cdc_event_id` STRING,
    `operation` STRING,
    `customer_id` BIGINT,
    `first_name` STRING,
    `last_name` STRING,
    `email` STRING,
    `country` STRING,
    `created_at` TIMESTAMP(6),
    `updated_at` TIMESTAMP(6),
    `source_version` STRING,
    `source_connector` STRING,
    `source_name` STRING,
    `source_ts_ms` BIGINT,
    `source_ts_us` BIGINT,
    `source_ts_ns` BIGINT,
    `source_snapshot` STRING,
    `source_database` STRING,
    `source_sequence` STRING,
    `source_schema` STRING,
    `source_table` STRING,
    `source_transaction_id` BIGINT,
    `source_lsn` BIGINT,
    `source_xmin` BIGINT,
    `source_origin` STRING,
    `source_origin_lsn` BIGINT,
    `transaction_id` STRING,
    `transaction_total_order` BIGINT,
    `transaction_data_collection_order` BIGINT,
    `debezium_ts_ms` BIGINT,
    `debezium_ts_us` BIGINT,
    `debezium_ts_ns` BIGINT,
    `source_event_at` TIMESTAMP(3),
    `debezium_processed_at` TIMESTAMP(3),
    `kafka_topic` STRING,
    `kafka_partition` INT,
    `kafka_offset` BIGINT,
    `kafka_timestamp` TIMESTAMP(3),
    `flink_ingested_at` TIMESTAMP(3),
    `processing_latency_ms` BIGINT
) WITH (
    'connector' = 'bigquery',
    'project' = '${GOOGLE_CLOUD_PROJECT}',
    'dataset' = 'retail_bronze',
    'table' = 'customers_cdc',
    'credentials.file' = '/run/secrets/gcp_adc',
    'write.delivery-guarantee' = 'exactly-once',
    'write.parallelism' = '2',
    'write.enable-table-creation' = 'true',
    'write.partition-field' = 'source_event_at',
    'write.partition-type' = 'DAY',
    'write.clustered-fields' = 'customer_id,operation',
    'write.region' = 'US'
);

CREATE TEMPORARY TABLE bq_products_cdc (
    `cdc_event_id` STRING,
    `operation` STRING,
    `product_id` BIGINT,
    `product_name` STRING,
    `category` STRING,
    `unit_price` DECIMAL(12, 2),
    `created_at` TIMESTAMP(6),
    `updated_at` TIMESTAMP(6),
    `source_version` STRING,
    `source_connector` STRING,
    `source_name` STRING,
    `source_ts_ms` BIGINT,
    `source_ts_us` BIGINT,
    `source_ts_ns` BIGINT,
    `source_snapshot` STRING,
    `source_database` STRING,
    `source_sequence` STRING,
    `source_schema` STRING,
    `source_table` STRING,
    `source_transaction_id` BIGINT,
    `source_lsn` BIGINT,
    `source_xmin` BIGINT,
    `source_origin` STRING,
    `source_origin_lsn` BIGINT,
    `transaction_id` STRING,
    `transaction_total_order` BIGINT,
    `transaction_data_collection_order` BIGINT,
    `debezium_ts_ms` BIGINT,
    `debezium_ts_us` BIGINT,
    `debezium_ts_ns` BIGINT,
    `source_event_at` TIMESTAMP(3),
    `debezium_processed_at` TIMESTAMP(3),
    `kafka_topic` STRING,
    `kafka_partition` INT,
    `kafka_offset` BIGINT,
    `kafka_timestamp` TIMESTAMP(3),
    `flink_ingested_at` TIMESTAMP(3),
    `processing_latency_ms` BIGINT
) WITH (
    'connector' = 'bigquery',
    'project' = '${GOOGLE_CLOUD_PROJECT}',
    'dataset' = 'retail_bronze',
    'table' = 'products_cdc',
    'credentials.file' = '/run/secrets/gcp_adc',
    'write.delivery-guarantee' = 'exactly-once',
    'write.parallelism' = '2',
    'write.enable-table-creation' = 'true',
    'write.partition-field' = 'source_event_at',
    'write.partition-type' = 'DAY',
    'write.clustered-fields' = 'product_id,operation',
    'write.region' = 'US'
);

CREATE TEMPORARY TABLE bq_orders_cdc (
    `cdc_event_id` STRING,
    `operation` STRING,
    `order_id` BIGINT,
    `customer_id` BIGINT,
    `order_date` TIMESTAMP(6),
    `status` STRING,
    `total_amount` DECIMAL(14, 2),
    `created_at` TIMESTAMP(6),
    `updated_at` TIMESTAMP(6),
    `source_version` STRING,
    `source_connector` STRING,
    `source_name` STRING,
    `source_ts_ms` BIGINT,
    `source_ts_us` BIGINT,
    `source_ts_ns` BIGINT,
    `source_snapshot` STRING,
    `source_database` STRING,
    `source_sequence` STRING,
    `source_schema` STRING,
    `source_table` STRING,
    `source_transaction_id` BIGINT,
    `source_lsn` BIGINT,
    `source_xmin` BIGINT,
    `source_origin` STRING,
    `source_origin_lsn` BIGINT,
    `transaction_id` STRING,
    `transaction_total_order` BIGINT,
    `transaction_data_collection_order` BIGINT,
    `debezium_ts_ms` BIGINT,
    `debezium_ts_us` BIGINT,
    `debezium_ts_ns` BIGINT,
    `source_event_at` TIMESTAMP(3),
    `debezium_processed_at` TIMESTAMP(3),
    `kafka_topic` STRING,
    `kafka_partition` INT,
    `kafka_offset` BIGINT,
    `kafka_timestamp` TIMESTAMP(3),
    `flink_ingested_at` TIMESTAMP(3),
    `processing_latency_ms` BIGINT
) WITH (
    'connector' = 'bigquery',
    'project' = '${GOOGLE_CLOUD_PROJECT}',
    'dataset' = 'retail_bronze',
    'table' = 'orders_cdc',
    'credentials.file' = '/run/secrets/gcp_adc',
    'write.delivery-guarantee' = 'exactly-once',
    'write.parallelism' = '2',
    'write.enable-table-creation' = 'true',
    'write.partition-field' = 'source_event_at',
    'write.partition-type' = 'DAY',
    'write.clustered-fields' = 'order_id,customer_id,operation',
    'write.region' = 'US'
);

CREATE TEMPORARY TABLE bq_order_items_cdc (
    `cdc_event_id` STRING,
    `operation` STRING,
    `order_item_id` BIGINT,
    `order_id` BIGINT,
    `product_id` BIGINT,
    `quantity` INT,
    `unit_price` DECIMAL(12, 2),
    `line_amount` DECIMAL(14, 2),
    `created_at` TIMESTAMP(6),
    `updated_at` TIMESTAMP(6),
    `source_version` STRING,
    `source_connector` STRING,
    `source_name` STRING,
    `source_ts_ms` BIGINT,
    `source_ts_us` BIGINT,
    `source_ts_ns` BIGINT,
    `source_snapshot` STRING,
    `source_database` STRING,
    `source_sequence` STRING,
    `source_schema` STRING,
    `source_table` STRING,
    `source_transaction_id` BIGINT,
    `source_lsn` BIGINT,
    `source_xmin` BIGINT,
    `source_origin` STRING,
    `source_origin_lsn` BIGINT,
    `transaction_id` STRING,
    `transaction_total_order` BIGINT,
    `transaction_data_collection_order` BIGINT,
    `debezium_ts_ms` BIGINT,
    `debezium_ts_us` BIGINT,
    `debezium_ts_ns` BIGINT,
    `source_event_at` TIMESTAMP(3),
    `debezium_processed_at` TIMESTAMP(3),
    `kafka_topic` STRING,
    `kafka_partition` INT,
    `kafka_offset` BIGINT,
    `kafka_timestamp` TIMESTAMP(3),
    `flink_ingested_at` TIMESTAMP(3),
    `processing_latency_ms` BIGINT
) WITH (
    'connector' = 'bigquery',
    'project' = '${GOOGLE_CLOUD_PROJECT}',
    'dataset' = 'retail_bronze',
    'table' = 'order_items_cdc',
    'credentials.file' = '/run/secrets/gcp_adc',
    'write.delivery-guarantee' = 'exactly-once',
    'write.parallelism' = '2',
    'write.enable-table-creation' = 'true',
    'write.partition-field' = 'source_event_at',
    'write.partition-type' = 'DAY',
    'write.clustered-fields' = 'order_item_id,order_id,product_id,operation',
    'write.region' = 'US'
);

CREATE TEMPORARY TABLE bq_order_metrics_5m (
    `window_start` TIMESTAMP(3),
    `window_end` TIMESTAMP(3),
    `order_count` BIGINT,
    `gross_revenue` DECIMAL(31, 2),
    `average_order_value` DECIMAL(31, 2),
    `unique_customers` BIGINT,
    `watermark_advanced_at` TIMESTAMP(3),
    `metric_generated_at` TIMESTAMP(3)
) WITH (
    'connector' = 'bigquery',
    'project' = '${GOOGLE_CLOUD_PROJECT}',
    'dataset' = 'retail_realtime',
    'table' = 'order_metrics_5m',
    'credentials.file' = '/run/secrets/gcp_adc',
    'write.delivery-guarantee' = 'exactly-once',
    'write.parallelism' = '2',
    'write.enable-table-creation' = 'true',
    'write.partition-field' = 'window_start',
    'write.partition-type' = 'DAY',
    'write.region' = 'US'
);
